### ISSUE TITLE
Not using the actual roll with Better Rolls

### ISSUE THREAD

**Issue by yoshifanx** [ElfFriend-DnD/foundryvtt-attack-roll-check-5e#1]
When using better rolls 5e, it seems to pull a random number for the check (see here: https://imgur.com/a/zYgdkPK)
D&D5e version 1.5.3
Modules Used
- BetterRolls5e
- Token Action Hud
- Actually Private Rolls
- Attack Roll Check DnD5E
- DnD5e UI

**Comment by akrigline** [comment]
Thanks for this report! Can you do me a favor and screenshot your Better Rolls settings as well?

**Comment by yoshifanx** [comment]
of course. Here you go: https://imgur.com/a/E650dTu

also i just tested and confirmed it's just Better Rolls that causes the issue. Having that disabled shows it properly.

**Comment by akrigline** [comment]
Alright I'll see what I can see, this might be a problem further up the chain the More Hooks 5e. We'll find out!

**Comment by akrigline** [comment]
I took a look and this is unfortunately much deeper than I am able to support quickly. For now I'm going to have to mark Better Rolls as incompatible and see if I can work with the author to get things working correctly.
