### ISSUE TITLE
[Question] Compatibility with Ready Set Roll for D&D 5e

### ISSUE THREAD

**Issue by vt-tom** [ElfFriend-DnD/foundryvtt-attack-roll-check-5e#10]
Hey, will this be compatible with Ready Set Roll for D&D 5e? Because both in combination are in my opinion one of the best alternatives to MidiQoL.
The Other Alternative is MRE and Retroactive Advantage.

**Comment by akrigline** [comment]
This was built with the core system's rolling hooks in mind.

I'm not terribly interested in complicating it with any extra compatibility logic, but if a PR was opened that didn't change much I would consider including it.

I don't know it's current compatibility status with either RSR or midi

**Comment by kaelad02** [comment]
I just tested this with the following versions:

- Foundry v10.291
- dnd5e v2.1.5
- RSR v1.5.1
- Attack Roll Check 2.1.0

It works from what I can tell but the Attack Roll Check message shows up before the attack result does (see screenshot below). I suspect that's just some quirk of how RSR works though. Is this good enough @vt-tom, can I close this issue?

![image](https://github.com/ElfFriend-DnD/foundryvtt-attack-roll-check-5e/assets/19502084/a86309fb-3b5e-4bf5-aaac-2b2448cbfa00)

**Comment by kaelad02** [comment]
I'm going to close this. OP can always reopen if necessary.
