### ISSUE TITLE
[Feature request] Consider adding setting for an optional rule

### ISSUE THREAD

**Issue by mech-tools** [ElfFriend-DnD/foundryvtt-attack-roll-check-5e#3]
Hello,

A popular Homebrew rule for the 5e system is the critical/fumble on +/- 10 (inspired by the PF2 system).

Would it be possible to implement it in this module?
If result >= AC + 10 === critical
If result <= AC - 10 === fumble

Optionally, the "10" value could be arbitrary and settable in a setting if the GM wanted "+/- 6" instead of "10".
And lastly, if we really, really wanted to make this option perfect, the chat card would display the exact delta between the result and the AC. (like AC: 10, Rolled: 21, +11, Critical!)

Also, this could be implemented for https://github.com/ElfFriend-DnD/foundryvtt-auto-roll-npc-save-5e as well

**Comment by akrigline** [comment]
Thanks for all the feedback!

I want to keep things as close to core as possible, so I'm not very interested in supporting this kind of optional rule. Also half the point of these tiny modules is that they have no config to mess with.

**Comment by mech-tools** [comment]
Ok.
Keep up the good work!
