### ISSUE TITLE
[BUG] Compatibility issue with Dice So Nice!

### ISSUE THREAD

**Issue by mech-tools** [ElfFriend-DnD/foundryvtt-attack-roll-check-5e#5]
Hello,

FVTT 9.242
Attack Roll Check 5e 1.1.0

Assuming the following activated modules:
![image](https://user-images.githubusercontent.com/1687854/149664607-e49ae5b5-61e2-4617-a7bc-4a1a30e3bcd1.png)

And the following Dice So Nice! configuration (note that "Display chat message immediately" is checked):
![image](https://user-images.githubusercontent.com/1687854/149664665-4f6a531c-aeb1-4620-9884-422fca590d16.png)

Immediately after charging the world, if a token tries a weapon attack on another token by targeting it.
The result of Attack Roll Check 5e is not displayed.
Instead, on the second roll (attack, damage, whatever), the result is shown.
It's like when "Display chat message immediately" is checked, Attack Roll Check 5e is one roll behind.

Example:
First roll:
![image](https://user-images.githubusercontent.com/1687854/149664878-7a427341-12c9-4e92-943e-09e246f8f942.png)

Note that no Attack Roll Check 5e card is displayed.

Second roll:
![image](https://user-images.githubusercontent.com/1687854/149664890-11fe4b88-543a-4890-9e9c-3058c2c7f117.png)

Note how the Attack Roll Check 5e card refers to the first roll.

**Comment by mech-tools** [comment]
Ok, I think I got it.

When the "Dice So Nice!" option `immediatelyDisplayChatMessages` is enabled, we don't need to wait for the Dice Animation to finish. In fact, Dice So Nice! calls the `diceSoNiceRollComplete` hook immediately (before the `Item5e.rollAttack`  hook is even called)

https://github.com/ElfFriend-DnD/foundryvtt-attack-roll-check-5e/blob/main/scripts/module.js#L83
This line should read:  
```if (game.modules.get('dice-so-nice')?.active && !game.settings.get('dice-so-nice', 'immediatelyDisplayChatMessages')) {```

⬆️ Not using the `diceSoNiceRollComplete` hook if the option `immediatelyDisplayChatMessages` is activated, because we don't need to wait for the roll to finish.

**Comment by akrigline** [comment]
Good find, thanks for looking into this!

Another case where a Pull request would be welcome so you could be marked as a contributor. :)

**Comment by mech-tools** [comment]
Already forked a version of this module with a lot of homebrew changes.
You have to do it yourself :)

**Comment by akrigline** [comment]
you can make a new branch off master without your changes

**Comment by mech-tools** [comment]
https://github.com/ElfFriend-DnD/foundryvtt-attack-roll-check-5e/pull/7
