### ISSUE TITLE
Incompatible with Whisper Box

### ISSUE THREAD

**Issue by fel-pt** [ElfFriend-DnD/foundryvtt-attack-roll-check-5e#8]
Just to let you know that Attack Roll Check doesn't work as intended with that module.

Since Attack Roll Check uses whispers to give the results to the DM, the Whisper Box will get filled with messages during combat.
![image](https://user-images.githubusercontent.com/79886727/153771231-9e3a4bff-3af3-4f06-b1d8-19f0de0ea5fe.png)

On top of that, the messages include information that the DM may not wish to share, such as the enemy's AC.

I'm also posting about the issue on Whisper Box's github: https://github.com/Sk1mble/WhisperBox/issues/16

**Comment by kaelad02** [comment]
The issue is with Whisper Box since it's not rendering the HTML. Can't fix it from this side.

I tested with Whisper Box v3.0.1 and saw that it works now though. I went through their releases and looks like they fixed it in version 3.0.0
